### PR TITLE
Create node.js.yml

### LINKED ISSUE #45: Setup CI
set up CI pipeline to enable:
1. auto build
2. code review (peer review by at least one of other team members)
3. regression test (find more details in testing plan template) will be executed when a commit is pushed to a major branch

### PR DESCRIPTION
**Pull request by DaniYoun**
test push for continuous integration
- closes #45

### CODE REVIEW

**Comment by DaniYoun** [comment]
This is still in draft, I'm just playing around with the github actions

**Comment by DaniYoun** [comment]
I learned so far we shouldn't keep the yml file in the subdirectories, since github won't recognize them unless the `.github` folder is in the root directory.

**Comment by DaniYoun** [comment]
okay, so basically the `working-directory` tag doesn't work with `uses`, and so I need to set the working directory for the whole job

**Comment by DaniYoun** [comment]
All green!
In summary,
1. we need to place the yml file on the root level
2. if we need to run actions on subdirectories (in our case server & client), we have to set the `working-directory` parameter
3. we also need to set the `cache-dependency-path` for the `uses` since they don't work with the working-directory parameter.
4. the node 14 runtime didn't like cors so I just removed it from our ci runtimes

**Review by hamdielzard — APPROVED** [review]

**Pull request merged**
